from . import ir_http
from . import mail_alias_domain
from . import mail_alias
from . import mail_gateway_allowed
from . import mail_mail
from . import mail_template
from . import mail_thread
from . import partner_devices
from . import res_config_settings
from . import res_users
