from odoo import fields, models


class PartnerDevice(models.Model):
    _inherit = 'mail.partner.device'

    keys = fields.Char(help=("It's refer to browser keys used by the notification: \n"
                             "- p256dh: It's the subscription public key generated by the browser. The browser will \n"
                             "          keep the private key secret and use it for decrypting the payload\n"
                             "- auth: The auth value should be treated as a secret and not shared outside of Viindoo"))
