# modules_website: module -> Viindoo intro/doc URL. Consumed by to_base's _load_manifest_plus
# (_get_brand_module_website) to override each module's `website` manifest field on a branded install.
# Do NOT delete: to_base imports odoo.addons.viin_brand.apriori.modules_website; a missing file
# silently reverts every module website to the Odoo default (see tests/ guard).
modules_website = {
    'account': 'https://viindoo.com/intro/invoicing',
    'board': 'https://viindoo.com/intro/dashboards',
    'calendar': 'https://viindoo.com/intro/calendar',
    'contacts': 'https://viindoo.com/intro/contact',
    'crm': 'https://viindoo.com/intro/crm',
    'fleet': 'https://viindoo.com/intro/fleet',
    'hr': 'https://viindoo.com/intro/employees',
    'hr_attendance': 'https://viindoo.com/intro/attendance',
    'hr_expense': 'https://viindoo.com/intro/expense',
    'hr_holidays': 'https://viindoo.com/intro/time-off',
    'hr_recruitment': 'https://viindoo.com/intro/recruitment',
    'hr_contract': 'https://viindoo.com/apps/modules/19.0/viin_hr_contract',
    'im_livechat': 'https://viindoo.com/intro/live-chat',
    'mail': 'https://viindoo.com/intro/discuss',
    'maintenance': 'https://viindoo.com/intro/maintenance',
    'mass_mailing': 'https://viindoo.com/intro/email-marketing',
    'mass_mailing_sms': 'https://viindoo.com/intro/sms-marketing',
    'mrp': 'https://viindoo.com/intro/mrp',
    'note': 'https://viindoo.com/intro/notes',
    'point_of_sale': 'https://viindoo.com/intro/pos',
    'purchase': 'https://viindoo.com/intro/purchase',
    'project': 'https://viindoo.com/intro/project',
    'repair': 'https://viindoo.com/intro/repair',
    'sale_management': 'https://viindoo.com/intro/sales',
    'stock': 'https://viindoo.com/intro/inventory',
    'survey': 'https://viindoo.com/intro/survey',
    'website': 'https://viindoo.com/intro/website',
    'website_blog': 'https://viindoo.com/intro/blogs',
    'website_event': 'https://viindoo.com/intro/event',
    'website_forum': 'https://viindoo.com/intro/app-forum',
    'website_sale': 'https://viindoo.com/intro/ecommerce',
    'website_slides': 'https://viindoo.com/intro/e-learning',
}
